language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t huiqzhang619/test-react -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true huiqzhang619/test-react npm test

after_success:
  - docker build -t huiqzhang619/multi-client ./client
  - docker build -t huiqzhang619/multi-nginx ./nginx
  - docker build -t huiqzhang619/multi-server ./server
  - docker build -t huiqzhang619/multi-worker ./worker
  # LOG IN TO THE DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # TAKE THOSE IMAGES AND PUSH THEM TO DOCKER HUB
  - docker push huiqzhang619/multi-client
  - docker push huiqzhang619/multi-nginx
  - docker push huiqzhang619/multi-server
  - docker push huiqzhang619/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "cn-northwest-1"
  app: "zhang-docker"
  env: "ZhangDocker-env"
  bucket_name: "elasticbeanstalk-cn-northwest-1-796401082536"
  bucket_path: "zhang-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
